"""rename department

Revision ID: 504f89919f62
Revises: bdbf7826f80e
Create Date: 2026-01-29 16:25:05.748696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504f89919f62'
down_revision = 'bdbf7826f80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments","department")
  
    # ### end Alembic commands ###
