"""rename address

Revision ID: 6371fba9c323
Revises: 504f89919f62
Create Date: 2026-01-29 16:31:05.819533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6371fba9c323'
down_revision = '504f89919f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("departments", schema=None) as batch_op:
       batch_op.alter_column('address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op :
       batch_op.alter_column('location', new_column_name='address')
    # ### end Alembic commands ###
